databases:
  - name: signalforge-db
    plan: basic-256mb

services:
  - type: web
    name: signal-forge
    plan: standard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn --bind 0.0.0.0:$PORT --worker-class eventlet --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: signalforge-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
